import { CodeBlock } from "./component/CodeBlock";
import { EndpointContainer } from "./component/EndpointContainer";
import {
  errorSample,
  formDataInterface,
  issueSampleCode,
  postSampleCode,
  reportInterface,
  serverResponseInterface,
} from "./data";
import "./styles/index.css";
import "./styles/documentationMediaQuerry.css";
import { Link } from "react-router-dom";

export default function Documentation() {
  return (
    <section className="documentation-section">
      <div className="api-reference">
        <div className="documentation-heading-container api-reference-heading-container">
          <h3>Api Overview</h3>
        </div>
        <div className="documentation-content api-reference-content">
          <p>
            The Crackspots API provides access to road infrastructure reports.
          </p>
          <p>
            The API is publicly accessible and does not require authentication
            or API keys. All data is exchanged in JSON format over standard HTTP
            requests.
          </p>
          <p>
            The API follows REST principles, using resource-oriented URLs,
            accepts form-encoded request bodies, returns JSON-encoded responses,
            and uses standard HTTP response codes, and verbs.
          </p>
        </div>
      </div>
      <div className="getting-started">
        <div className="documentation-heading-container getting-started-heading-container">
          <h4>Getting started</h4>
        </div>
        <div className="documentation-content getting-started-content">
          <p>
            This section will guide you through making your first request to the
            API.
          </p>
          <h4>Basic requests</h4>
          <p>The base URL for all endpoints is:</p>
          <EndpointContainer content="https://crackspots-server.onrender.com/api/v1" />
          <div className="reports-overview-container">
            <div className="descriptions report-description">
              <h5>Reports</h5>
              <p>
                Reports are structured summaries of user submitted data
                collected in the system.
              </p>
              <p>
                Each report is represented as a structured object
                containing:{" "}
              </p>
              <CodeBlock content={reportInterface} heading="Report Interface" />
              <h5>Issues</h5>
              <p>
                An issue is a <span className="highlight">system-defined </span>{" "}
                representation of road infrastructure defects, formed by
                grouping reports that describe the same damage at a specific
                location.
              </p>
              <p>
                They are not created by users; they are generated by the server
                when reports are sufficiently close in distance, 5 meters, and
                occur on the <span className="highlight">same street.</span>
              </p>
              <p>
                They represent persistent road problems and serve as the base
                for visualization and interaction within the application.
              </p>
              <p>
                Each report is assigned an{" "}
                <span className="highlight">issueId</span>, which is used to
                group reports that refer to the same underlying road defect.
              </p>
              <CodeBlock
                heading="Grouping reports into issues"
                content={issueSampleCode}
              />
            </div>
            <div className="descriptions fetching-report-description">
              <h5>Fetching reports</h5>
              <p>
                All reports are accessible through a{" "}
                <span className="get-highlight">GET</span> request to the{" "}
                <code className="endPoint">/reports</code> endpoint.
              </p>
              <p>
                This endpoint returns a response object containing a{" "}
                <span className="response-highlight">success</span> flag and an{" "}
                <span className="response-highlight">array</span> of report
                objects.
              </p>
              <CodeBlock content={serverResponseInterface} />
            </div>
            <div className="descriptions create-reports-description">
              <h5>Create a Report</h5>
              <p>
                To create a report, a{" "}
                <span className="post-highlight">POST</span> request is sent to
                the <code className="endPoint">/reports</code> endpoint.
              </p>
              <p>
                This request should have appended to the body, a{" "}
                <span className="highlight">multipart/form-data</span> and
                include the following fields:
              </p>
              <div className="api-table">
                <div className="api-table-header">Field</div>
                <div className="api-table-header">Type</div>
                <div className="api-table-header">Required</div>
                <div className="api-table-header">Description</div>

                <div>file</div>
                <div>File</div>
                <div>Yes</div>
                <div>
                  The image file representing the report (e.g. road damage). Max
                  size: 12MB.
                </div>
                <div>coordinates</div>
                <div>String</div>
                <div>Yes</div>
                <div>
                  A JSON string containing the geographic coordinates of the
                  report location.
                </div>
                <div>severity</div>
                <div>Enum</div>
                <div>Yes</div>
                <div>
                  A string containing an esimated condition of the extent of the
                  damage.
                </div>
              </div>
              <CodeBlock
                content={formDataInterface}
                heading="formData interface"
              />
              <CodeBlock content={postSampleCode} heading="sample code" />
              <div className="note">
                <h5>Note:</h5>
                <p>Reports submitted should be within Nairobi county.</p>
                <p>
                  <span>
                    <Link to="/about#about-section-design-considerations">
                      See reason.
                    </Link>
                  </span>
                </p>
              </div>
            </div>
            <div className="descriptions error-descriptions">
              <h5>Errors</h5>
              <p>
                Whenever a request to the back-end is unsuccessful, the server
                returns a JSON error response describing what failed.
              </p>
              <p>
                This simplifiies understanding what went wrong and how to
                resolve the issue.
              </p>
              <CodeBlock heading="Server response" content={errorSample} />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
